config/routes.rb
Rails.application.routes.draw do
  
  root to: "user/homes#top"
  get '/about' => "user/homes#about"
    
  devise_for :users, skip: [:passwords,], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }
  
    get 'users' => "user/users#top"
    get 'users/mypage' => "user/users#show"
    get 'users/mypage/edit' => "user/users#edit"
    patch 'users/update' => "user/users#update"
    
    get 'users/bank_categories' => "user/bank_categories#index"
    post 'users/bank_categories' => "user/bank_categories#create"
    get 'users/bank_categories/:id/edit' => "user/bank_categories#edit",as: "edit_users_bank_categories"
    patch 'users/bank_categories/:id' => "user/bank_categories#update", as: "update_users_bank_categories"
    delete 'users/bank_categories/:id' => "user/bank_categories#destroy", as: "destroy_users_bank_categories"
    
    get 'users/banks' =>"user/banks#index"
    get 'users/banks/new'=>"user/banks#new"
    get 'users/banks/:id'=>"user/banks#show", as: "users_bank"
    post 'users/banks'=>"user/banks#create"
    get 'users/banks/:id/edit'=>"user/banks#edit",as: "edit_bank"
    patch 'users/banks/:id'=>"user/banks#update"
    delete 'users/banks/:id'=>"user/banks#destroy"
    
    get 'users/bank_logs' => "user/bank_logs#index"
    get 'users/bank_logs/new' => "user/bank_logs#new"
    get 'users/bank_logs/:id' => "user/bank_logs#show",as: "bank_log"
    post 'users/bank_logs' => "user/bank_logs#create"
    get 'users/bank_logs/:id/edit' => "user/bank_logs#edit",as: "edit_bank_log"
    patch 'users/bank_logs/:id' => "user/bank_logs#update"
    delete 'users/bank_logs/:id' => "user/bank_logs#destroy"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bank_log.rb
class BankLog < ApplicationRecord
    
    belongs_to :bank
    
    belongs_to :bank_category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :last_name, presence: true

  validates :first_name, presence: true

  validates :account_name, presence: true, uniqueness: true
  
  has_many :banks

end

app/controllers/user/bank_categories_controller.rb
class User::BankCategoriesController < ApplicationController
  def index
    @categories = BankCategory.where(user_id: current_user.id)
    @category = BankCategory.new
  end
  
  def create
    @category = BankCategory.new(category_params)
    @category.user_id = current_user.id
    if @category.save
      redirect_to users_bank_categories_path
    else
      @categories = BankCategory.where(user_id: current_user.id)
      render :index
    end
  end

  def edit
    @category = BankCategory.find(params[:id])
  end
  
  def update
    @category = BankCategory.find(params[:id])
    if @category.update(category_params)
      redirect_to users_bank_categories_path
    else
      render :edit
    end
  end
  
  def destroy
    @category = BankCategory.find(params[:id])
    @category.destroy
    redirect_to users_bank_categories_path
  end
  
  private
  
  def category_params
    params.require(:bank_category).permit(:name)
  end
end

app/controllers/user/bank_logs_controller.rb
class User::BankLogsController < ApplicationController
  def index
  end
  
  def create
    @bank_log = BankLog.new(bank_log_params)
    @bank_log.user_id = current_user.id
    if @bank_log.save
      redirect_to bank_log_path(@bank_log)
    else
      render :new
    end
  end

  def show
    @bank_log = BankLog.find(params[:id])
  end

  def new
    @bank_log = BankLog.new
  end

  def edit
    @bank_log = BankLog.find(params[:id])
  end
  
  def update
    @bank_log = BankLog.find(params[:id])
    if @bank_log.update(bank_log_params)
      redirect_to bank_log_path(@bank_log)
    else
      render :edit
    end
  end
  
  def destroy
    @bank_log = BankLog.find(params[:id])
    @bank = Bank.find(params[:id])
    @bank_log.destroy
    redirect_to users_mypage_path
  end
  
  private
  
  def bank_log_params
    params.require(:bank_log).permit(:title, :bank_category_id, :use_date, :detail, :amount_money, :in_out, :bank_id)
  end
end

app/controllers/user/banks_controller.rb
class User::BanksController < ApplicationController
  
  def index
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    @banks = Bank.where(user_id: current_user.id)
    @bank_logs = BankLog.where(use_date: @month.all_month, user_id: current_user.id).order(use_date: "ASC")
  end

  def show
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    @bank = Bank.find(params[:id])
    @bank_logs = @bank.bank_logs.where(use_date: @month.all_month, user_id: current_user.id).order(use_date: "ASC")
    @bank_logs.each do |bank_log|
      @total = 0
      if bank_log.in_out == true
        @total -= bank_log.amount_money
      else
        @total += bank_log.amount_money
      end
    end
  end
  
  def new
    @bank = Bank.new
  end
  
  def create
    @bank = Bank.new(bank_params)
    @bank.user_id = current_user.id
    if @bank.save
      redirect_to users_bank_path(@bank)
    else
      render :new
    end
  end

  def edit
    @bank = Bank.find(params[:id])
  end
  
  def update
    @bank = Bank.find(params[:id])
    if @bank.update(bank_params)
      redirect_to users_bank_path(@bank)
    else
      render :edit
    end
  end
  
  def destroy
    @bank = Bank.find(params[:id])
    @bank.destroy
    redirect_to users_mypage_path
  end
  
  private
  
  def bank_params
    params.require(:bank).permit(:name, :branch, :owner)
  end
  
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :account_name, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :account_name, :email])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    users_mypage_path
  end
  
  def after_update_path_for(resource)
    users_mypage_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:account_name, :email])
  end
  
  def after_sign_in_path_for(resource)
    users_mypage_path
  end
  
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def top
  end

  def show
    @banks = Bank.where(user_id: current_user.id)
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to users_mypage_path
    else
      render user_mypage_edit_path
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:last_name, :first_name, :account_name, :email)
  end
end

app/helpers/user/bank_categories_helper.rb
module User::BankCategoriesHelper
end

app/helpers/user/bank_logs_helper.rb
module User::BankLogsHelper
end

app/helpers/user/banks_helper.rb
module User::BanksHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/bank_logs/edit.html.erb
<%= render "layouts/header" %>
<div class="container">
    <div class="row">
        <div class="col mx-auto">
            <h2 class="text-center">Edit Bank log</h2><br></br>
            
            <%= form_with model: @bank_log, url: bank_log_path, method: :patch do |f| %>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">In or Out</label>
                  <div class="col-sm-10">
                    <%= f.select :in_out, [['In',0],['Out',1]], { include_blank: "Please select In or Out" }, autofocus: true, class: "form-control" %>
                  </div>
                </div>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">Bank Name</label>
                  <div class="col-sm-10">
                    <%= f.collection_select :bank_id, Bank.where(user_id: current_user.id), :id, :name, prompt: "Please select a bank", autofocus: true, class: "form-control" %>
                  </div>
                </div>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">Use Date</label>
                  <div class="col-sm-10">
                    <%= f.date_field :use_date, autofocus: true, placeholder: "date", class: "form-control" %>
                  </div>
                </div>
                
                <div class="row">
                    <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">Category</label>
                    <div class="col-sm-10">
                      <%= f.collection_select :bank_category_id, BankCategory.where(user_id: current_user.id), :id, :name, prompt: "Please select a category", class: "form-select" %>
                    </div>
                </div>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">Title</label>
                  <div class="col-sm-10">
                    <%= f.text_field :title, autofocus: true, placeholder: "shoe fee", class: "form-control" %>
                  </div>
                </div>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">Amount Of Money</label>
                  <div class="col-sm-10">
                    <%= f.text_field :amount_money, autofocus: true, placeholder: "3980", class: "form-control" %>
                  </div>
                </div>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">Detail</label>
                  <div class="col-sm-10">
                    <%= f.text_field :detail, autofocus: true, placeholder: "Please describe the details of the log.", class: "form-control" %>
                  </div>
                </div>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg"></label>
                  <div class="col">
                    <%= f.submit "Upda Log", class: "btn btn-warning form-control" %>
                  </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/user/bank_logs/index.html.erb
<h1>User::BankLogs#index</h1>
<p>Find me in app/views/user/bank_logs/index.html.erb</p>

多分

app/views/user/bank_logs/new.html.erb
<%= render "layouts/header" %>
<div class="container">
    <div class="row">
        <div class="col mx-auto">
            <h2 class="text-center">Add Bank log</h2><br></br>
            
            <%= form_with model: @bank_log, url: users_bank_logs_path, method: :post do |f| %>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">In or Out</label>
                  <div class="col-sm-10">
                    <%= f.select :in_out, [['In',0],['Out',1]], { include_blank: "Please select In or Out" }, autofocus: true, class: "form-control" %>
                  </div>
                </div>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">Bank Name</label>
                  <div class="col-sm-10">
                    <%= f.collection_select :bank_id, Bank.where(user_id: current_user.id), :id, :name, prompt: "Please select a bank", autofocus: true, class: "form-control" %>
                  </div>
                </div>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">Use Date</label>
                  <div class="col-sm-10">
                    <%= f.date_field :use_date, autofocus: true, placeholder: "date", class: "form-control" %>
                  </div>
                </div>
                
                <div class="row">
                    <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">Category</label>
                    <div class="col-sm-10">
                      <%= f.collection_select :bank_category_id, BankCategory.where(user_id: current_user.id), :id, :name, prompt: "Please select a category", class: "form-select" %>
                    </div>
                </div>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">Title</label>
                  <div class="col-sm-10">
                    <%= f.text_field :title, autofocus: true, placeholder: "shoe fee", class: "form-control" %>
                  </div>
                </div>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">Amount Of Money</label>
                  <div class="col-sm-10">
                    <%= f.text_field :amount_money, autofocus: true, placeholder: "3980", class: "form-control" %>
                  </div>
                </div>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg text-center">Detail</label>
                  <div class="col-sm-10">
                    <%= f.text_field :detail, autofocus: true, placeholder: "Please describe the details of the log.", class: "form-control" %>
                  </div>
                </div>
                
                <div class="row">
                  <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg"></label>
                  <div class="col">
                    <%= f.submit "Create Log", class: "btn btn-warning form-control" %>
                  </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/user/bank_logs/show.html.erb
<%= render "layouts/header" %>
<div class="container">
    <h2 class="text-center">Bank Log Detail</h2><br></br>
    <div class="row">
        <div class="col-3">
            <h3 class="text-center">Bank Info</h3>
            </br>
            <table class="table">
                <tbody>
                    <tr>
                        <th>Bank Name</th>
                        <th>
                            <%= link_to users_bank_path(@bank_log.bank) do %>
                                <%= @bank_log.bank.name %>
                            <% end %>
                        </th>
                    </tr>
                    <tr>
                        <th>Branch Name</th>
                        <th><%= @bank_log.bank.branch %></th>
                    </tr>
                    <tr>
                        <th>Owner</th>
                        <th><%= @bank_log.bank.owner %></th>
                    </tr>
                    <tr>
                        <th>Total Blance</th>
                        <th>¥100000</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-9">
            <h3 class="text-center">Detail</h3>
            </br>
            <table class="table">
                <thaed>
                    <tr>
                        <td class="col-1">Date</td>
                        <td class="col-2">Category</td>
                        <td class="col-3">Title</td>
                        <td class="col-4">Detail</td>
                        <td class="col-2">Amount</td>
                    </tr>
                </thaed>
                <tbody>
                    <tr>
                        <td><%= @bank_log.use_date.strftime('%m/%d') %></td>
                        <td><%= @bank_log.bank_category.name %></td>
                        <td><%= @bank_log.title %></td>
                        <td><%= @bank_log.detail %></td>
                        <td>
                            <% if @bank_log.in_out == true %>
                                <p class="text-danger">- ¥<%= @bank_log.amount_money %></p>
                            <% else %>
                                <p class="text-success">+ ¥<%= @bank_log.amount_money %></p>
                            <% end %>
                        </td>
                    </tr>
                </tbody>
            </table>
            <%= link_to "Edit Log", edit_bank_log_path(@bank_log), class: "btn btn-info btn-block" %>
            <%= link_to "Destroy Log", bank_log_path(@bank_log), method: :delete, class: "btn btn-danger btn-block", "data-confirm" => "Do you really want to delete this?" %>
        </div>
    </div>
</div>