config/routes.rb
Rails.application.routes.draw do
  
  root to: "user/homes#top"
  get '/about' => "user/homes#about"
    
  devise_for :users, skip: [:passwords,], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }
  
    get 'users' => "user/users#top"
    get 'users/mypage' => "user/users#show"
    get 'users/mypage/edit' => "user/users#edit"
    patch 'users/update' => "user/users#update"
    
    get 'users/bank_categories' => "user/bank_categories#index"
    post 'users/bank_categories' => "user/bank_categories#create"
    get 'users/bank_categories/:id/edit' => "user/bank_categories#edit",as: "edit_users_bank_categories"
    patch 'users/bank_categories/:id' => "user/bank_categories#update", as: "update_users_bank_categories"
    delete 'users/bank_categories/:id' => "user/bank_categories#destroy", as: "destroy_users_bank_categories"
    
    get 'users/banks' =>"user/banks#index"
    get 'users/banks/new'=>"user/banks#new"
    get 'users/banks/:id'=>"user/banks#show", as: "users_bank"
    post 'users/banks'=>"user/banks#create"
    get 'users/banks/:id/edit'=>"user/banks#edit",as: "edit_bank"
    patch 'users/banks/:id'=>"user/banks#update"
    delete 'users/banks/:id'=>"user/banks#destroy"
    
    get 'users/bank_logs' => "user/bank_logs#index"
    get 'users/bank_logs/new' => "user/bank_logs#new"
    get 'users/bank_logs/:id' => "user/bank_logs#show",as: "bank_log"
    post 'users/bank_logs' => "user/bank_logs#create"
    get 'users/bank_logs/:id/edit' => "user/bank_logs#edit",as: "edit_bank_log"
    patch 'users/bank_logs/:id' => "user/bank_logs#update"
    delete 'users/bank_logs/:id' => "user/bank_logs#destroy"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
    
    belongs_to :user
    
    has_many :bank_logs
    
    has_many :middle_banks
end

app/models/bank_category.rb
class BankCategory < ApplicationRecord
    
    has_many :banks
    
end

app/models/bank_log.rb
class BankLog < ApplicationRecord
    
    belongs_to :bank
    
    belongs_to :bank_category
end

app/models/middle_bank.rb
class MiddleBank < ApplicationRecord
    
    belongs_to :bank
    
    belongs_to :bank_log
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :last_name, presence: true

  validates :first_name, presence: true

  validates :account_name, presence: true, uniqueness: true
  
  has_many :banks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/bank_logs_controller.rb
class User::BankLogsController < ApplicationController
  def index
  end
  
  def create
    @bank_log = BankLog.new(bank_log_params)
    @bank_log.user_id = current_user.id
    if @bank_log.save
      redirect_to bank_log_path(@bank_log)
    else
      render :new
    end
  end

  def show
    @bank_log = BankLog.find(params[:id])
  end

  def new
    @bank_log = BankLog.new
  end

  def edit
    @bank_log = BankLog.find(params[:id])
  end
  
  def update
    @bank_log = BankLog.find(params[:id])
    if @bank_log.update(bank_log_params)
      redirect_to bank_log_path(@bank_log)
    else
      render :edit
    end
  end
  
  def destroy
    @bank_log = BankLog.find(params[:id])
    @bank = Bank.find(params[:id])
    @bank_log.destroy
    redirect_to users_mypage_path
  end
  
  private
  
  def bank_log_params
    params.require(:bank_log).permit(:title, :bank_category_id, :use_date, :detail, :amount_money, :in_out, :bank_id)
  end
end

app/controllers/user/banks_controller.rb
class User::BanksController < ApplicationController
  
  def index
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    @banks = Bank.where(user_id: current_user.id)
    @bank_logs = BankLog.where(use_date: @month.all_month, user_id: current_user.id).order(use_date: "ASC")
  end

  def show
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    @bank = Bank.find(params[:id])
    @bank_logs = @bank.bank_logs.where(use_date: @month.all_month, user_id: current_user.id).order(use_date: "ASC")
    @bank_logs.each do |bank_log|
      @total = 0
      if bank_log.in_out == true
        @total -= bank_log.amount_money
      else
        @total += bank_log.amount_money
      end
    end
  end
  
  def new
    @bank = Bank.new
  end
  
  def create
    @bank = Bank.new(bank_params)
    @bank.user_id = current_user.id
    if @bank.save
      redirect_to users_bank_path(@bank)
    else
      render :new
    end
  end

  def edit
    @bank = Bank.find(params[:id])
  end
  
  def update
    @bank = Bank.find(params[:id])
    if @bank.update(bank_params)
      redirect_to users_bank_path(@bank)
    else
      render :edit
    end
  end
  
  def destroy
    @bank = Bank.find(params[:id])
    @bank.destroy
    redirect_to users_mypage_path
  end
  
  private
  
  def bank_params
    params.require(:bank).permit(:name, :branch, :owner)
  end
  
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:account_name, :email])
  end
  
  def after_sign_in_path_for(resource)
    users_mypage_path
  end
  
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def top
  end

  def show
    @banks = Bank.where(user_id: current_user.id)
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to users_mypage_path
    else
      render user_mypage_edit_path
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:last_name, :first_name, :account_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/bank_categories_helper.rb
module User::BankCategoriesHelper
end

app/helpers/user/bank_logs_helper.rb
module User::BankLogsHelper
end

app/helpers/user/banks_helper.rb
module User::BanksHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3 class="text-center"><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <% obj.errors.full_messages.each do |message| %>
        <p class="text-center"><%= message %></p>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
    <div class="container">
        <br>
        <div class="row justify-content-between">
            <div class="col-4">
                <h4><%= link_to "Money Log", root_path, class: "text-danger" %></h4>
            </div>
            <div class="col-6">
                 <div class="d-flex flex-row-reverse">
                    <% if user_signed_in? %>
                    <ul class="nav">
                        <li class="nav-item nav-link"><%= link_to "Top", users_path %></li>
                        <li class="nav-item nav-link"><%= link_to "About", about_path %></li>
                        <li class="nav-item nav-link"><%= link_to "Bank", users_banks_path %></li>
                        <li class="nav-item nav-link"><%= link_to "Card", about_path %></li>
                        <li class="nav-item nav-link"><%= link_to "My Page", users_mypage_path %></li>
                        <li class="nav-aitem nav-link"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                    </ul>
                    <% else %>
                    <ul class="nav">
                        <li class="nav-item nav-link"><%= link_to "Top", root_path %></li>
                        <li class="nav-item nav-link"><%= link_to "About", about_path %></li>
                        <li class="nav-item nav-link"><%= link_to "Sign Up", new_user_registration_path %></li>
                        <li class="nav-item nav-link"><%= link_to "Log In", new_user_session_path %></li>
                    </ul>
                    <% end %>
                 </div>
            </div>
        </div>
    </div>
    <hr>
    </br>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>-->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>-->
    <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>-->

    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
    <footer>
      <br></br>
      <hr></hr>
      </br>
      <p class="text-center">Money Log</p>
      <br></br>
    </footer>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <div class="row">
      <div class="col-4">
        <div class="text-left">
          <%= link_to t('simple_calendar.previous', default: '<< Previous'), calendar.url_for_previous_view, class: "btn btn-secondary" %>
        </div>
      </div>
      <div class="col-4">
        <div class="text-center">
          <h3 class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></h3>
        </div>
      </div>
      <div class="col-4">
        <div class="text-right">
          <%= link_to t('simple_calendar.next', default: 'Next >>'), calendar.url_for_next_view, class: "btn btn-secondary text-right" %>
        </div>
      </div>
    </div>
</div>
  </br>
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_table.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <div class="row">
      <div class="col-4">
        <div class="text-left">
          <%= link_to t('simple_calendar.previous', default: '<< Previous'), calendar.url_for_previous_view, class: "btn btn-secondary" %>
        </div>
      </div>
      <div class="col-4">
        <div class="text-center">
          <h3 class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></h3>
        </div>
      </div>
      <div class="col-4">
        <div class="text-right">
          <%= link_to t('simple_calendar.next', default: 'Next >>'), calendar.url_for_next_view, class: "btn btn-secondary text-right" %>
        </div>
      </div>
    </div>
  </div>
  </br>
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>